#! /usr/bin/env bash
# do-release [ <action> ]

[ "$1" ] && OPT_ACTION=$1 || OPT_ACTION="release"

if [ "$OPT_ACTION" == "release" ]; then
	rm -f "do-tag" "do-release"
elif [ "$OPT_ACTION" == "name" ]; then
	echo "Application Template"
else
	echo "Unknown action: $OPT_ACTION" >&2; exit 1
fi
